In [47]:
#importing library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [48]:
#loading the dataset
df=pd.read_csv('../input/voicegender/voice.csv')

In [49]:
df

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0     0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1     0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2     0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3     0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4     0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
...        ...       ...       ...       ...       ...       ...        ...   
3163  0.131884  0.084734  0.153707  0.049285  0.201144  0.151859   1.762129   
3164  0.116221  0.089221  0.076758  0.042718  0.204911  0.162193   0.693730   
3165  0.142056  0.095798  0.183731  0.033424  0.224360  0.190936   1.876502   
3166  0.143659  0.090628  0.184976  0.043508  0.219943  0.176435   1.591065   
3167  0.165509  0.092884  0.183044  0.070072  0.250827  0.180756   1.705029   

             kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0      274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1      634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2     1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3        4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4        4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   
...           ...       ...       ...  ...       ...       ...       ...   
3163     6.630383  0.962934  0.763182  ...  0.131884  0.182790  0.083770   
3164     2.503954  0.960716  0.709570  ...  0.116221  0.188980  0.034409   
3165     6.604509  0.946854  0.654196  ...  0.142056  0.209918  0.039506   
3166     5.388298  0.950436  0.675470  ...  0.143659  0.172375  0.034483   
3167     5.769115  0.938829  0.601529  ...  0.165509  0.185607  0.062257   

        maxfun   meandom    mindom    maxdom   dfrange   modindx   label  
0     0.275862  0.007812  0.007812  0.007812  0.000000  0.000000    male  
1     0.250000  0.009014  0.007812  0.054688  0.046875  0.052632    male  
2     0.271186  0.007990  0.007812  0.015625  0.007812  0.046512    male  
3     0.250000  0.201497  0.007812  0.562500  0.554688  0.247119    male  
4     0.266667  0.712812  0.007812  5.484375  5.476562  0.208274    male  
...        ...       ...       ...       ...       ...       ...     ...  
3163  0.262295  0.832899  0.007812  4.210938  4.203125  0.161929  female  
3164  0.275862  0.909856  0.039062  3.679688  3.640625  0.277897  female  
3165  0.275862  0.494271  0.007812  2.937500  2.929688  0.194759  female  
3166  0.250000  0.791360  0.007812  3.593750  3.585938  0.311002  female  
3167  0.271186  0.227022  0.007812  0.554688  0.546875  0.350000  female  

[3168 rows x 21 columns]

In [50]:
#checking for missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3168 entries, 0 to 3167
Data columns (total 21 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   meanfreq  3168 non-null   float64
 1   sd        3168 non-null   float64
 2   median    3168 non-null   float64
 3   Q25       3168 non-null   float64
 4   Q75       3168 non-null   float64
 5   IQR       3168 non-null   float64
 6   skew      3168 non-null   float64
 7   kurt      3168 non-null   float64
 8   sp.ent    3168 non-null   float64
 9   sfm       3168 non-null   float64
 10  mode      3168 non-null   float64
 11  centroid  3168 non-null   float64
 12  meanfun   3168 non-null   float64
 13  minfun    3168 non-null   float64
 14  maxfun    3168 non-null   float64
 15  meandom   3168 non-null   float64
 16  mindom    3168 non-null   float64
 17  maxdom    3168 non-null   float64
 18  dfrange   3168 non-null   float64
 19  modindx   3168 non-null   float64
 20  label     3168 non-null   obje

In [51]:
#encoding label
label_encoder=LabelEncoder()
df['label']=label_encoder.fit_transform(df['label'])


In [52]:
df['label']

0       1
1       1
2       1
3       1
4       1
       ..
3163    0
3164    0
3165    0
3166    0
3167    0
Name: label, Length: 3168, dtype: int64

In [53]:
#checking for mapping with dictionary
dict(enumerate(label_encoder.classes_))

{0: 'female', 1: 'male'}

In [54]:
df

meanfreq        sd    median       Q25       Q75       IQR       skew  \
0     0.059781  0.064241  0.032027  0.015071  0.090193  0.075122  12.863462   
1     0.066009  0.067310  0.040229  0.019414  0.092666  0.073252  22.423285   
2     0.077316  0.083829  0.036718  0.008701  0.131908  0.123207  30.757155   
3     0.151228  0.072111  0.158011  0.096582  0.207955  0.111374   1.232831   
4     0.135120  0.079146  0.124656  0.078720  0.206045  0.127325   1.101174   
...        ...       ...       ...       ...       ...       ...        ...   
3163  0.131884  0.084734  0.153707  0.049285  0.201144  0.151859   1.762129   
3164  0.116221  0.089221  0.076758  0.042718  0.204911  0.162193   0.693730   
3165  0.142056  0.095798  0.183731  0.033424  0.224360  0.190936   1.876502   
3166  0.143659  0.090628  0.184976  0.043508  0.219943  0.176435   1.591065   
3167  0.165509  0.092884  0.183044  0.070072  0.250827  0.180756   1.705029   

             kurt    sp.ent       sfm  ...  centroid   meanfun    minfun  \
0      274.402906  0.893369  0.491918  ...  0.059781  0.084279  0.015702   
1      634.613855  0.892193  0.513724  ...  0.066009  0.107937  0.015826   
2     1024.927705  0.846389  0.478905  ...  0.077316  0.098706  0.015656   
3        4.177296  0.963322  0.727232  ...  0.151228  0.088965  0.017798   
4        4.333713  0.971955  0.783568  ...  0.135120  0.106398  0.016931   
...           ...       ...       ...  ...       ...       ...       ...   
3163     6.630383  0.962934  0.763182  ...  0.131884  0.182790  0.083770   
3164     2.503954  0.960716  0.709570  ...  0.116221  0.188980  0.034409   
3165     6.604509  0.946854  0.654196  ...  0.142056  0.209918  0.039506   
3166     5.388298  0.950436  0.675470  ...  0.143659  0.172375  0.034483   
3167     5.769115  0.938829  0.601529  ...  0.165509  0.185607  0.062257   

        maxfun   meandom    mindom    maxdom   dfrange   modindx  label  
0     0.275862  0.007812  0.007812  0.007812  0.000000  0.000000      1  
1     0.250000  0.009014  0.007812  0.054688  0.046875  0.052632      1  
2     0.271186  0.007990  0.007812  0.015625  0.007812  0.046512      1  
3     0.250000  0.201497  0.007812  0.562500  0.554688  0.247119      1  
4     0.266667  0.712812  0.007812  5.484375  5.476562  0.208274      1  
...        ...       ...       ...       ...       ...       ...    ...  
3163  0.262295  0.832899  0.007812  4.210938  4.203125  0.161929      0  
3164  0.275862  0.909856  0.039062  3.679688  3.640625  0.277897      0  
3165  0.275862  0.494271  0.007812  2.937500  2.929688  0.194759      0  
3166  0.250000  0.791360  0.007812  3.593750  3.585938  0.311002      0  
3167  0.271186  0.227022  0.007812  0.554688  0.546875  0.350000      0  

[3168 rows x 21 columns]

In [55]:
#Splitting and scaling the dataset
y=df['label'].copy()
x=df.drop('label',axis=1).copy()

In [56]:
#scaling the dataset
scaler=StandardScaler()
x=scaler.fit_transform(x)

In [57]:
x

array([[-4.04924806,  0.4273553 , -4.22490077, ..., -1.43142165,
        -1.41913712, -1.45477229],
       [-3.84105325,  0.6116695 , -3.99929342, ..., -1.41810716,
        -1.4058184 , -1.01410294],
       [-3.46306647,  1.60384791, -4.09585052, ..., -1.42920257,
        -1.41691733, -1.06534356],
       ...,
       [-1.29877326,  2.32272355, -0.05197279, ..., -0.5992661 ,
        -0.58671739,  0.17588664],
       [-1.2452018 ,  2.012196  , -0.01772849, ..., -0.41286326,
        -0.40025537,  1.14916112],
       [-0.51474626,  2.14765111, -0.07087873, ..., -1.27608595,
        -1.2637521 ,  1.47567886]])

In [58]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=42)

In [59]:
x_train

array([[ 0.6062224 ,  0.56931149,  0.7770935 , ...,  1.31580119,
         1.3245183 , -0.60075897],
       [ 1.04345699, -0.87327782,  0.68378988, ...,  0.62344778,
         0.63194508, -0.0529519 ],
       [-1.56456085,  0.43680145, -2.08411215, ..., -0.47277846,
        -0.46018959, -0.67164701],
       ...,
       [ 0.71628666,  0.35285606,  0.99919377, ...,  0.67670573,
         0.68521995, -0.67244475],
       [ 0.02983232,  0.05862641,  0.17650263, ..., -0.19539328,
        -0.18715592, -0.9330489 ],
       [-0.44043779,  0.54648806, -0.37779616, ...,  0.27727107,
         0.28565848, -0.42171608]])

In [60]:
x.shape

(3168, 20)

In [67]:
#constructing the model
inputs=tf.keras.Input(shape=(x.shape[1],))
X=tf.keras.layers.Dense(64,activation='relu')(inputs)
X=tf.keras.layers.Dense(64,activation='relu')(X)
outputs=tf.keras.layers.Dense(1,activation='sigmoid')(X)
model=tf.keras.Model(inputs,outputs)

In [68]:
#getting the summary of the model
model.summary()

Model: "model_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_4 (InputLayer)         [(None, 20)]              0         
_________________________________________________________________
dense_9 (Dense)              (None, 64)                1344      
_________________________________________________________________
dense_10 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_11 (Dense)             (None, 1)                 65        
Total params: 5,569
Trainable params: 5,569
Non-trainable params: 0
_________________________________________________________________


In [69]:
#compiling the model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=[
            'accuracy',tf.keras.metrics.AUC(name='auc')
    ])
history=model.fit(
    x_train,
    y_train,
    validation_split=0.2,
    batch_size=32,
    epochs=100,
    callbacks=[
            tf.keras.callbacks.EarlyStopping(
            monitor='val_loss')
    ])

Epoch 1/100
56/56 [==============================] - 1s 13ms/step - loss: 0.3962 - accuracy: 0.8770 - auc: 0.9392 - val_loss: 0.2069 - val_accuracy: 0.9572 - val_auc: 0.9899


In [70]:
model.evaluate(x_test,y_test)

30/30 [==============================] - 0s 1ms/step - loss: 0.2055 - accuracy: 0.9506 - auc: 0.9889


[0.2054683417081833, 0.9505783319473267, 0.9889447689056396]

# Using 2D CNNs

In [71]:
x

array([[-4.04924806,  0.4273553 , -4.22490077, ..., -1.43142165,
        -1.41913712, -1.45477229],
       [-3.84105325,  0.6116695 , -3.99929342, ..., -1.41810716,
        -1.4058184 , -1.01410294],
       [-3.46306647,  1.60384791, -4.09585052, ..., -1.42920257,
        -1.41691733, -1.06534356],
       ...,
       [-1.29877326,  2.32272355, -0.05197279, ..., -0.5992661 ,
        -0.58671739,  0.17588664],
       [-1.2452018 ,  2.012196  , -0.01772849, ..., -0.41286326,
        -0.40025537,  1.14916112],
       [-0.51474626,  2.14765111, -0.07087873, ..., -1.27608595,
        -1.2637521 ,  1.47567886]])

In [66]:
x

array([[-4.04924806,  0.4273553 , -4.22490077, ..., -1.43142165,
        -1.41913712, -1.45477229],
       [-3.84105325,  0.6116695 , -3.99929342, ..., -1.41810716,
        -1.4058184 , -1.01410294],
       [-3.46306647,  1.60384791, -4.09585052, ..., -1.42920257,
        -1.41691733, -1.06534356],
       ...,
       [-1.29877326,  2.32272355, -0.05197279, ..., -0.5992661 ,
        -0.58671739,  0.17588664],
       [-1.2452018 ,  2.012196  , -0.01772849, ..., -0.41286326,
        -0.40025537,  1.14916112],
       [-0.51474626,  2.14765111, -0.07087873, ..., -1.27608595,
        -1.2637521 ,  1.47567886]])

In [75]:
x=pd.DataFrame(tf.keras.preprocessing.sequence.pad_sequences(x,dtype=np.float,maxlen=25,padding='post'))

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [76]:
x

0         1         2         3         4         5         6   \
0    -4.049248  0.427355 -4.224901 -2.576102 -5.693607 -0.214778  2.293306   
1    -3.841053  0.611669 -3.999293 -2.486885 -5.588987 -0.258485  4.548056   
2    -3.463066  1.603848 -4.095851 -2.706986 -3.928699  0.909326  6.513656   
3    -0.992157  0.899998 -0.759454 -0.901418 -0.711205  0.632690 -0.449858   
4    -1.530640  1.322561 -1.676948 -1.268395 -0.792029  1.005588 -0.480911   
...        ...       ...       ...       ...       ...       ...       ...   
3163 -1.638842  1.658182 -0.877839 -1.873163 -0.999378  1.579141 -0.325020   
3164 -2.162452  1.927682 -2.994482 -2.008095 -0.840021  1.820721 -0.577009   
3165 -1.298773  2.322724 -0.051973 -2.199039 -0.017123  2.492666 -0.298044   
3166 -1.245202  2.012196 -0.017728 -1.991852 -0.204021  2.153653 -0.365367   
3167 -0.514746  2.147651 -0.070879 -1.446089  1.102679  2.254671 -0.338487   

            7         8         9   ...        15        16        17  \
0     1.762946 -0.039083  0.471575  ... -1.564205 -0.708404 -1.431422   
1     4.433008 -0.065236  0.594431  ... -1.561916 -0.708404 -1.418107   
2     7.326207 -1.083730  0.398261  ... -1.563866 -0.708404 -1.429203   
3    -0.240099  1.516383  1.797340  ... -1.195367 -0.708404 -1.273867   
4    -0.238940  1.708336  2.114740  ... -0.221660 -0.708404  0.124154   
...        ...       ...       ...  ...       ...       ...       ...   
3163 -0.221916  1.507749  1.999883  ...  0.007024 -0.708404 -0.237556   
3164 -0.252503  1.458418  1.697831  ...  0.153573 -0.214641 -0.388453   
3165 -0.222108  1.150198  1.385857  ... -0.637833 -0.708404 -0.599266   
3166 -0.231123  1.229850  1.505711  ... -0.072080 -0.708404 -0.412863   
3167 -0.228300  0.971759  1.089126  ... -1.146760 -0.708404 -1.276086   

            18        19   20   21   22   23   24  
0    -1.419137 -1.454772  0.0  0.0  0.0  0.0  0.0  
1    -1.405818 -1.014103  0.0  0.0  0.0  0.0  0.0  
2    -1.416917 -1.065344  0.0  0.0  0.0  0.0  0.0  
3    -1.261532  0.614286  0.0  0.0  0.0  0.0  0.0  
4     0.136933  0.289046  0.0  0.0  0.0  0.0  0.0  
...        ...       ...  ...  ...  ...  ...  ...  
3163 -0.224892 -0.098989  0.0  0.0  0.0  0.0  0.0  
3164 -0.384717  0.871981  0.0  0.0  0.0  0.0  0.0  
3165 -0.586717  0.175887  0.0  0.0  0.0  0.0  0.0  
3166 -0.400255  1.149161  0.0  0.0  0.0  0.0  0.0  
3167 -1.263752  1.475679  0.0  0.0  0.0  0.0  0.0  

[3168 rows x 25 columns]

In [85]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(2217, 20)
(951, 20)
(2217,)
(951,)
